import React, { useState, useRef } from 'react';
import html2canvas from 'html2canvas';
import { toast } from 'sonner';
import api from "../api/api";
import {
  Box,
  Typography,
  Button,
  Paper,
  Card,
  CardContent,
  Chip,
  Divider,
  TextField,
  Avatar,
  Grid,
  Tooltip
} from "@mui/material";
import {
  ArrowBack,
  BarChart,
  TrendingUp,
  TrendingDown,
  Info,
  AssignmentTurnedIn,
  Person,
  Event,
  Assistant,
  Grade,
  Download,
  PictureAsPdf
} from '@mui/icons-material';
import { Bar } from 'react-chartjs-2';

const AssessmentDetail = ({
  assessment,
  team,
  colors,
  getPerformanceColor,
  getCategoryChartData,
  isMobile,
  onBack,
  getLabelForCheckpoint,
  onExportExcel
}) => {
  const [exportingPDF, setExportingPDF] = useState(false);
  const chartRef = useRef(null);

  const handleExportToPDF = async () => {
    try {
      setExportingPDF(true);

      // 1. Capture Chart as Image if available
      let chartImage = "";
      if (chartRef.current) {
        const canvas = await html2canvas(chartRef.current, {
          backgroundColor: colors.surface,
          scale: 2, // Higher quality
          logging: false,
          useCORS: true
        });
        chartImage = canvas.toDataURL("image/png");
      }

      // 2. Construct Markdown Report
      const strengths = assessment.checkPoints
        .filter(cp => cp.score >= 4)
        .map(cp => `* **${cp.name}**: ${getLabelForCheckpoint(cp.name, cp.score)}`)
        .join('\n');

      const weaknesses = assessment.checkPoints
        .filter(cp => cp.score < 3)
        .map(cp => `* **${cp.name}**: ${getLabelForCheckpoint(cp.name, cp.score)}`)
        .join('\n');

      const auditLogs = assessment.checkPoints
        .map(p => `| ${p.name} | ${p.score}/5 | ${getLabelForCheckpoint(p.name, p.score)} | ${p.notes ? p.notes.replace(/\n/g, ' ') : '-'} |`)
        .join('\n');

      const reportMarkdown = `
# Performance Audit Report: ${team.teamName}

**Audit Date**: ${new Date(assessment.assessmentDate).toLocaleDateString(undefined, { dateStyle: 'long' })}
**Conducted By**: ${assessment.conductedBy}
**Overall Proficiency**: ${Math.round(assessment.overallScore)}%

## 📊 Proficiency Visualization
${chartImage ? `![Proficiency Chart](${chartImage})` : "_Chart visualization not available_"}

## 🧠 Cognitive Insights

### 🏆 Core Strengths
${strengths || "No major strengths identified in this audit."}

### 🛠️ Growth Opportunities
${weaknesses || "No critical weaknesses identified in this audit."}

## 📋 Detailed Audit Logs
| Checkpoint | Score | Status | Specialist Observations |
| :--- | :---: | :--- | :--- |
${auditLogs}

## ✍️ Auditor's Final Synthesis
${assessment.feedback || "No additional qualitative feedback provided."}

---
*Generated by Reach Quality Assessors*
`;

      // 3. Call Backend API
      const reportTitle = `${team.teamName.replace(/\s+/g, '_')}_Assessment_${new Date(assessment.assessmentDate).toISOString().split('T')[0]}`;

      const response = await api.post('/ai/report/download', {
        reportContent: reportMarkdown,
        title: `Performance Audit: ${team.teamName}`,
        format: 'pdf'
      }, {
        responseType: 'blob'
      });

      // 4. Trigger Download
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `${reportTitle}.pdf`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);

      toast.success("PDF Report generated successfully");
    } catch (error) {
      console.error("PDF Export Error:", error);
      toast.error("Failed to generate PDF report");
    } finally {
      setExportingPDF(false);
    }
  };

  const glassStyle = {
    background: colors.surface,
    backdropFilter: 'blur(16px) saturate(180%)',
    WebkitBackdropFilter: 'blur(16px) saturate(180%)',
    border: `1px solid ${colors.border}`,
    borderRadius: '24px',
    boxShadow: '0 8px 32px 0 rgba(0, 0, 0, 0.37)'
  };

  // Custom chart data and options
  const chartData = getCategoryChartData();
  const chartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    indexAxis: isMobile ? 'y' : 'x',
    plugins: {
      legend: { display: false },
      tooltip: {
        callbacks: {
          label: (ctx) => `${ctx.parsed}% Proficiency`
        }
      }
    },
    scales: {
      x: { max: 100, grid: { color: colors.border }, ticks: { color: colors.textSecondary } },
      y: { max: 100, grid: { color: colors.border }, ticks: { color: colors.textSecondary } }
    }
  };

  // Compute stats
  const checkpointStrengths = assessment.checkPoints.filter(cp => cp.score >= 4);
  const checkpointWeaknesses = assessment.checkPoints.filter(cp => cp.score < 3);

  return (
    <Box sx={{ mt: 2 }}>
      <Box className="no-print" sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 4 }}>
        <Button
          startIcon={<ArrowBack />}
          onClick={onBack}
          sx={{
            color: colors.textSecondary,
            textTransform: 'none',
            '&:hover': { color: colors.primary, bgcolor: colors.primaryHover }
          }}
        >
          Back to Unit History
        </Button>

        <Box sx={{ display: 'flex', gap: 2 }}>
          <Button
            variant="outlined"
            startIcon={<PictureAsPdf />}
            onClick={handleExportToPDF}
            disabled={exportingPDF}
            sx={{
              borderColor: colors.border,
              color: colors.textPrimary,
              borderRadius: '12px',
              textTransform: 'none',
              ...glassStyle,
              '&:hover': { borderColor: colors.primary, bgcolor: colors.primaryHover }
            }}
          >
            {exportingPDF ? "Generating..." : "Export to PDF"}
          </Button>
          <Button
            variant="outlined"
            startIcon={<Download />}
            onClick={onExportExcel}
            sx={{
              borderColor: colors.border,
              color: colors.textPrimary,
              borderRadius: '12px',
              textTransform: 'none',
              ...glassStyle,
              '&:hover': { borderColor: colors.primary, bgcolor: colors.primaryHover }
            }}
          >
            Export to Excel
          </Button>
        </Box>
      </Box>



      {/* Premium Report Header */}
      <Card sx={{ ...glassStyle, p: 4, mb: 4, position: 'relative', overflow: 'hidden' }}>
        <Box sx={{
          position: 'absolute',
          top: -20,
          right: -20,
          width: 150,
          height: 150,
          borderRadius: '50%',
          bgcolor: `${colors[getPerformanceColor(assessment.overallScore)]}15`,
          filter: 'blur(40px)'
        }} />

        <Grid container spacing={4} alignItems="center">
          <Grid item xs={12} md={8}>
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, mb: 1 }}>
              <Grade sx={{ color: colors.warning }} />
              <Typography variant="h4" sx={{ fontWeight: 800, color: colors.textPrimary }}>
                Performance Audit Report
              </Typography>
            </Box>
            <Typography variant="body1" sx={{ color: colors.textSecondary, mb: 3 }}>
              Detailed assessment analysis for <strong>{team.teamName}</strong> conducted by <strong>{assessment.conductedBy}</strong>
            </Typography>

            <Grid container spacing={3}>
              <Grid item xs={6} sm={4}>
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                  <Event sx={{ fontSize: 18, color: colors.primary }} />
                  <Typography variant="caption" sx={{ color: colors.textSecondary }}>Audit Date</Typography>
                </Box>
                <Typography variant="body2" sx={{ fontWeight: 700 }}>
                  {new Date(assessment.assessmentDate).toLocaleDateString(undefined, { dateStyle: 'long' })}
                </Typography>
              </Grid>
              <Grid item xs={6} sm={4}>
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                  <AssignmentTurnedIn sx={{ fontSize: 18, color: colors.success }} />
                  <Typography variant="caption" sx={{ color: colors.textSecondary }}>Verification</Typography>
                </Box>
                <Typography variant="body2" sx={{ fontWeight: 700 }}>Compliance Validated</Typography>
              </Grid>
            </Grid>
          </Grid>

          <Grid item xs={12} md={4}>
            <Box sx={{
              p: 3,
              borderRadius: '20px',
              bgcolor: 'rgba(255,255,255,0.03)',
              border: `1px solid ${colors.border}`,
              textAlign: 'center'
            }}>
              <Typography variant="caption" sx={{ color: colors.textSecondary, mb: 1, display: 'block' }}>
                Overall Proficiency
              </Typography>
              <Typography variant="h2" sx={{
                fontWeight: 900,
                color: colors[getPerformanceColor(assessment.overallScore)],
                mb: 1
              }}>
                {Math.round(assessment.overallScore || 0)}%
              </Typography>
              <Chip
                label={getLabelForCheckpoint('', Math.round(assessment.overallScore / 20))}
                sx={{
                  bgcolor: `${colors[getPerformanceColor(assessment.overallScore)]}20`,
                  color: colors[getPerformanceColor(assessment.overallScore)],
                  fontWeight: 800,
                  px: 2
                }}
              />
            </Box>
          </Grid>
        </Grid>
      </Card>

      {/* Analytics Section */}
      <Grid container spacing={4} sx={{ mb: 4 }}>
        <Grid item xs={12} lg={7}>
          <Paper sx={{ ...glassStyle, p: 4, height: '100%' }}>
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: 3 }}>
              <BarChart sx={{ color: colors.primary }} />
              <Typography variant="h6" sx={{ fontWeight: 700 }}>Proficiency Breakdown</Typography>
            </Box>
            <Box ref={chartRef} sx={{ height: 400 }}>
              {chartData && <Bar data={chartData} options={chartOptions} />}
            </Box>
          </Paper>
        </Grid>

        <Grid item xs={12} lg={5}>
          <Paper sx={{ ...glassStyle, p: 4, height: '100%' }}>
            <Typography variant="h6" sx={{ fontWeight: 700, mb: 4 }}>Cognitive Insights</Typography>

            <Box sx={{ mb: 4 }}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, color: colors.success, mb: 2 }}>
                <TrendingUp fontSize="small" />
                <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>Core Strengths</Typography>
              </Box>
              {checkpointStrengths.slice(0, 3).map((cp, idx) => (
                <Box key={idx} sx={{ p: 1.5, mb: 1.5, bgcolor: 'rgba(16, 185, 129, 0.05)', borderRadius: '12px', border: '1px solid rgba(16, 185, 129, 0.1)' }}>
                  <Typography variant="body2" sx={{ fontWeight: 600 }}>{cp.name}</Typography>
                  <Typography variant="caption" sx={{ color: colors.textSecondary }}>Level: {getLabelForCheckpoint(cp.name, cp.score)}</Typography>
                </Box>
              ))}
            </Box>

            <Box>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, color: colors.error, mb: 2 }}>
                <TrendingDown fontSize="small" />
                <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>Growth Opportunities</Typography>
              </Box>
              {checkpointWeaknesses.slice(0, 3).map((cp, idx) => (
                <Box key={idx} sx={{ p: 1.5, mb: 1.5, bgcolor: 'rgba(239, 68, 68, 0.05)', borderRadius: '12px', border: '1px solid rgba(239, 68, 68, 0.1)' }}>
                  <Typography variant="body2" sx={{ fontWeight: 600 }}>{cp.name}</Typography>
                  <Typography variant="caption" sx={{ color: colors.textSecondary }}>Issue: {getLabelForCheckpoint(cp.name, cp.score)}</Typography>
                </Box>
              ))}
            </Box>
          </Paper>
        </Grid>
      </Grid>

      {/* Detailed Checkpoints */}
      <Paper sx={{ ...glassStyle, p: 4, mb: 4 }}>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: 4 }}>
          <Assistant sx={{ color: colors.primary }} />
          <Typography variant="h6" sx={{ fontWeight: 700 }}>Detailed Audit Logs</Typography>
        </Box>

        {assessment.checkPoints.map((point, index) => (
          <Box key={index} sx={{ mb: 4 }}>
            <Box sx={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', mb: 1 }}>
              <Box>
                <Typography variant="subtitle1" sx={{ fontWeight: 700, mb: 0.5 }}>{point.name}</Typography>
                <Typography variant="body2" sx={{ color: colors.textSecondary }}>{point.description}</Typography>
              </Box>
              <Box sx={{ display: 'flex', gap: 1, alignItems: 'center' }}>
                <Chip
                  label={`${point.score}/5`}
                  size="small"
                  sx={{ bgcolor: `${colors[getPerformanceColor(point.score)]}15`, color: colors[getPerformanceColor(point.score)], fontWeight: 800 }}
                />
                <Chip
                  label={getLabelForCheckpoint(point.name, point.score)}
                  size="small"
                  sx={{ bgcolor: colors[getPerformanceColor(point.score)], color: 'white', fontWeight: 600 }}
                />
              </Box>
            </Box>

            {point.notes && (
              <Box sx={{ mt: 2, p: 2, bgcolor: 'rgba(255,255,255,0.02)', borderRadius: '12px', borderLeft: `4px solid ${colors.primary}` }}>
                <Typography variant="caption" sx={{ color: colors.textSecondary, mb: 0.5, display: 'block' }}>Specialist Observations:</Typography>
                <Typography variant="body2" sx={{ direction: 'rtl', textAlign: 'right', color: colors.textPrimary }}>{point.notes}</Typography>
              </Box>
            )}

            {index < assessment.checkPoints.length - 1 && <Divider sx={{ mt: 4, borderColor: colors.border }} />}
          </Box>
        ))}
      </Paper>

      {/* Auditor Feedback */}
      <Paper sx={{ ...glassStyle, p: 4, mb: 6 }}>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mb: 3 }}>
          <Info sx={{ color: colors.primary }} />
          <Typography variant="h6" sx={{ fontWeight: 700 }}>Auditor's Final Synthesis</Typography>
        </Box>
        <Typography variant="body1" sx={{
          p: 3,
          bgcolor: 'rgba(255,255,255,0.02)',
          borderRadius: '16px',
          border: `1px solid ${colors.border}`,
          color: colors.textPrimary,
          direction: 'rtl',
          textAlign: 'right',
          whiteSpace: 'pre-wrap'
        }}>
          {assessment.feedback || "No additional qualitative feedback provided."}
        </Typography>
      </Paper>
    </Box>
  );
};

export default AssessmentDetail;