import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  user: localStorage.getItem("userInfo") ? JSON.parse(localStorage.getItem("userInfo")) : null,
  token: localStorage.getItem("accessToken") ? localStorage.getItem("accessToken") : null,
};

const authSlice = createSlice({
  name: "auth",
  initialState,
  reducers: {
    login: (state, action) => {
      state.user = action.payload.user;
      state.token = action.payload.token;
      localStorage.setItem("userInfo", JSON.stringify(action.payload.user));
      localStorage.setItem("accessToken", action.payload.token);
    },
    logout: (state) => {
      state.user = null;
      state.token = null;
      localStorage.removeItem("userInfo");
      localStorage.removeItem("accessToken");
    },
    updateUser: (state, action) => {
      state.user = action.payload;
      localStorage.setItem("userInfo", JSON.stringify(action.payload));
    },
    setIsSidebarOpen: (state, action) => {
      state.isSidebarOpen = action.payload;
    },
  },
});

export const { login, logout, updateUser, setIsSidebarOpen } = authSlice.actions;

export default authSlice.reducer;
// To simplify what this export, it export the initialState or updated initialState object.
// What Does export default authSlice.reducer Export?
// When you export authSlice.reducer, you are exporting the reducer function generated by createSlice (from Redux Toolkit). This reducer function is responsible for handling state updates for the auth slice of your Redux store.
// Key Points:
//   1. Reducer Function:
//     A reducer is a pure function that takes the current state and an action, and returns the new state.
//     The reducer function generated by createSlice automatically handles the state updates based on the actions defined in the reducers field of the slice.
//   2. Initial State:
//     The initialState is defined inside the slice, but it is not directly exported by authSlice.reducer.
//     The reducer function uses the initialState as the default state when the Redux store is first initialized.
//   3. State Updates:
//     The reducer function updates the state based on the actions dispatched to it.
//     For example, if you dispatch an action like login, the reducer will update the state according to the logic defined in the login reducer.